logzio:
  url: https://listener.logz.io:8071
  token: TOKEN

settings:
  time_interval: 1

auth_apis:
  - type: cisco_secure_x
    id: 1e98d35f67648ffd1cac
    key: 221a50a2-a35e-47be-9042-af98d1a0d231
    filters:
      - key: start_date
        value: 2021-07-01T00%3A00%3A00%2B00%3A00


oauth_apis:
  - type: azure_graph
    id: ID
    key: KEY
    filters:
      - FILTER_1
      - FILTER_2
  - type: general
    token_url:
    data_url:
    data_json_path:
    next_url_json_path:
    id: ID
    key: KEY
    filters:
      - FILTER_1
      - FILTER_2