name: End-to-End Tests
on: [push]
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install docker
          pip install requests
      - name: Run E2E tests
        env:
          LOGZIO_API_TOKEN: ${{ secrets.LOGZIO_API_TOKEN }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          LOGZIO_SHIPPING_TOKEN: ${{ secrets.LOGZIO_SHIPPING_TOKEN }}
        run: python -m unittest discover -s e2e_tests/apis -p "*.py"