name: Integration test
on: [pull_request]
jobs:
  e2e_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: | 
          pip install -r requirements.txt
          pip install pytest
      - name: Run api fetcher
        env:
          AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
          AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          AZURE_AD_SECRET_VALUE: ${{ secrets.AZURE_AD_SECRET_VALUE }}
          LOGZIO_SHIPPING_TOKEN: ${{ secrets.LOGZIO_SHIPPING_TOKEN }}
        run: |
          PYTHONPATH=. python3 ./tests/IntegrationTests/test_shipping.py &
          echo $! > script_pid.txt
      - name: Wait, to allow logs to get processed and indexed in logzio
        run: sleep 120
      - name: Check Logzio for logs
        env:
          LOGZIO_API_TOKEN: ${{ secrets.LOGZIO_API_TOKEN }}
        run: PYTHONPATH=. pytest ./tests/IntegrationTests/test_data_arrived.py
